# .github/workflows/build.yml
# GitHub Actions configuration file for building wheels
# See https://github.com/pypa/cibuildwheel for details

name: build

on:
  push:
    branches: [python/dev]
  pull_request:
    branches: [python/dev]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform }}-${{ matrix.manylinux_image }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # 32-bit Linux manylinux2014
          - os: ubuntu-latest
            python: 37
            platform: manylinux_i686
            manylinux_image: manylinux2014

          # 64-bit Linux manylinux2014
          - os: ubuntu-latest
            python: 37
            platform: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python: 38
            platform: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python: 39
            platform: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python: 310
            platform: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python: 311
            platform: manylinux_x86_64
            manylinux_image: manylinux2014

          # 64-bit macOS x86_64
          - os: macos-latest
            python: 37
            platform: macosx_x86_64
          - os: macos-latest
            python: 38
            platform: macosx_x86_64
          - os: macos-latest
            python: 39
            platform: macosx_x86_64
          - os: macos-latest
            python: 310
            platform: macosx_x86_64
          - os: macos-latest
            python: 311
            platform: macosx_x86_64

          # 64-bit macOS arm64
          - os: macos-latest
            python: 38
            platform: macosx_arm64
          - os: macos-latest
            python: 39
            platform: macosx_arm64
          - os: macos-latest
            python: 310
            platform: macosx_arm64
          - os: macos-latest
            python: 311
            platform: macosx_arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and test wheels
        uses: pypa/cibuildwheel@v2.12.1
        env:
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform }}
          CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux_image }}
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl

  upload_anaconda:
    name: Upload to Anaconda
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    needs: build_wheels

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Upload artifacts to Anaconda
        run: bash tools/github/upload_anaconda.sh
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
