name: documentation

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  run:
    name: Publish documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build and publish the documentation
        env:
          CNAME: pdfo.net
          COMMIT_MESSAGE: Publish documentation
          DOC_BRANCH: gh-pages
        run: |
          # Install dependencies
          python -m pip install --progress-bar=off .[doc]
          
          # Build the documentation
          export BUILDDIR=/tmp/pdfo-doc
          (
          cd doc || exit
          make html
          )
          
          # Configure git
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          
          # Publish the documentation
          git switch "${{ env.DOC_BRANCH }}" || git switch -c "${{ env.DOC_BRANCH }}"
          git rm -r '*' 2> /dev/null || true
          git clean -fxd
          mv $BUILDDIR/html/* .
          : > .nojekyll
          echo "${{ env.CNAME }}" > CNAME
          git add -A
          git commit -m "${{ env.COMMIT_MESSAGE }}"
          git push -f origin "${{ env.DOC_BRANCH }}"
